// react-lbxx/src/views/login.js
import React ,{Component}from 'react'
import {Input,Button} from 'antd' 

class Login extends Component{
    state={
        username:'',
        password:'',
        checked:[true,false]
    }
    loginIn=()=>{
        const {username,password} = this.state

        this.mock_url('/zhiyuan/login',{username,password}).then(data=>{
            if(Object.is(data.code,0)){
                
                localStorage.setItem('username',username)
                localStorage.setItem('rolename',data.data)
                this.props.history.push('/home')
                return 
            }
            alert(data.msg)
        })
    }
    render(){
        const {username,password,checked} = this.state
        return <div>
                <Input value={username} type="text" onChange={(ev)=>this.setState({username:ev.target.value})}/>
                <Input value={password} type="password" onChange={(ev)=>this.setState({password:ev.target.value})}/>
                <Button onClick={()=>this.loginIn()}>登录</Button>

                


           
            </div>
    }
}

export default Login

// 摸底考试/vue-app/src/views/login.vue
<template>
  <div class="login">
    <div>用户邮箱<input type="text" v-model="email"/></div>
    <div>用户密码 <input type="text" v-model="password"/></div>
    <button @click="loginIn">登录</button>
    <p @click="$router.push('/re')">没有账号，去注册</p> 
  </div>
</template>
<script>
export default {
  data(){
    return{
        email:'',
        password:''
    } 
  },
  methods:{
    loginIn(){
        let {email,password} = this 
        if(email===''||password===''){
                alert('用户名或密码不能为空')
                return
        } 
        this.$Mockurl('/login/data',{email,password}).then(data=>{
          console.log(data)
            if(data.code===0){
                 localStorage.setItem('username',data.data.username)
                 localStorage.setItem('email',data.data.email)
                 localStorage.setItem('img',data.data.img)
                 this.$router.push('/home')
                 return
            }
            alert(data.msg)
        })
    }
  }
}
</script>
